name: sync clankers
on:
  schedule:
    - cron: '*/2 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Clankers
        run: |
          curl --request GET 'https://clank.fun/api/sync-clankers' --header 'Authorization: Bearer ${{ secrets.CRON_SECRET }}'